apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base
- pod.yml

configMapGenerator:
  - name: monitor-config
    envs: 
      - .env

generatorOptions:
  disableNameSuffixHash: true
