version: "3"

networks:
  atuin:
  proxy:

volumes:
  atuin-database-data:

services:
  atuin-database:
    image: docker.io/postgres:14-alpine
    environment:
      - POSTGRES_USER=${ATUIN_DB_USERNAME}
      - POSTGRES_PASSWORD=${ATUIN_DB_PASSWORD}
      - POSTGRES_DB=${ATUIN_DB_DATABASE_NAME}
    expose:
      - 5432 # db
    extends:
      file: common.yml
      service: log-to-json
    healthcheck:
      test: pg_isready
    networks:
      - atuin
    restart: unless-stopped
    volumes:
      - atuin-database-data:/var/lib/postgresql/data

  atuin:
    image: ghcr.io/atuinsh/atuin:18.0.1
    command: server start
    depends_on:
      atuin-database:
        condition: service_healthy
    environment:
      - ATUIN_HOST=0.0.0.0
      - ATUIN_OPEN_REGISTRATION=false
      - ATUIN_DB_URI=postgres://${ATUIN_DB_USERNAME}:${ATUIN_DB_PASSWORD}@atuin-database/${ATUIN_DB_DATABASE_NAME}
      - TZ=${TIMEZONE}
    expose:
      - 8888 # api
    extends:
      file: common.yml
      service: log-to-json
    networks:
      - proxy
      - atuin
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
