networks:
  proxy:
  authelia:
  ldap:

volumes:
  authelia-data:
  authelia-database-data:
  authelia-redis-data:
  lldap-data:

services:
  authelia:
    image: docker.io/authelia/authelia:4.39.2
    depends_on:
      authelia-redis:
        condition: service_healthy
      authelia-database:
        condition: service_healthy
    environment:
      - X_AUTHELIA_CONFIG_FILTERS=template
      - PROXY_PUBLIC_DOMAIN=${PROXY_PUBLIC_DOMAIN}
      - PROXY_REDIRECT_TO=https://code.${PROXY_PUBLIC_DOMAIN}
      - AUTHELIA_TOTP_ISSUER=${PROXY_PUBLIC_DOMAIN}
      - AUTHELIA_IDENTITY_VALIDATION_RESET_PASSWORD_JWT_SECRET=${AUTHELIA_JWT_SECRET}
      - AUTHELIA_SESSION_REDIS_HOST=authelia-redis
      - AUTHELIA_SESSION_REDIS_PORT=6379
      - AUTHELIA_SESSION_SECRET=${AUTHELIA_SESSION_SECRET}
      - AUTHELIA_STORAGE_POSTGRES_ADDRESS=authelia-database
      - AUTHELIA_STORAGE_POSTGRES_USERNAME=${AUTHELIA_DB_USERNAME}
      - AUTHELIA_STORAGE_POSTGRES_PASSWORD=${AUTHELIA_DB_PASSWORD}
      - AUTHELIA_STORAGE_POSTGRES_DATABASE=${AUTHELIA_DB_DATABASE_NAME}
      - AUTHELIA_STORAGE_ENCRYPTION_KEY=${AUTHELIA_STORAGE_ENCRYPTION_KEY}
      - AUTHELIA_NOTIFIER_SMTP_ADDRESS=${AUTHELIA_SMTP_ADDRESS}
      - AUTHELIA_NOTIFIER_SMTP_USERNAME=${AUTHELIA_SMTP_USERNAME}
      - AUTHELIA_NOTIFIER_SMTP_PASSWORD=${AUTHELIA_SMTP_PASSWORD}
      - AUTHELIA_NOTIFIER_SMTP_SENDER=${AUTHELIA_SMTP_SENDER}
      - AUTHELIA_AUTHENTICATION_BACKEND_LDAP_BASE_DN=${LLDAP_BASE_DN}
      - AUTHELIA_AUTHENTICATION_BACKEND_LDAP_ADDRESS=ldap://lldap:3890
      - AUTHELIA_AUTHENTICATION_BACKEND_LDAP_USER=uid=authelia,ou=people,${LLDAP_BASE_DN}
      - AUTHELIA_AUTHENTICATION_BACKEND_LDAP_PASSWORD=${AUTHELIA_LDAP_PASSWORD}
      - TZ=${TIMEZONE}
    expose:
      - 9091 # api
    extends:
      file: common.yml
      service: log-to-json
    healthcheck:
      disable: false
    networks:
      - proxy
      - authelia
      - ldap
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - authelia-data:/config
      - ./authelia/configuration.yml:/config/configuration.yml:ro

  authelia-redis:
    image: docker.io/redis:7-alpine
    expose:
      - 6379 # api
    extends:
      file: common.yml
      service: log-to-json
    healthcheck:
      test: redis-cli ping
    networks:
      - authelia
    restart: unless-stopped
    volumes:
      - authelia-redis-data:/data

  authelia-database:
    image: docker.io/postgres:14-alpine
    environment:
      - POSTGRES_USER=${AUTHELIA_DB_USERNAME}
      - POSTGRES_PASSWORD=${AUTHELIA_DB_PASSWORD}
      - POSTGRES_DB=${AUTHELIA_DB_DATABASE_NAME}
    expose:
      - 5432 # db
    extends:
      file: common.yml
      service: log-to-json
    healthcheck:
      test: pg_isready --dbname='${AUTHELIA_DB_DATABASE_NAME}' --username='${AUTHELIA_DB_USERNAME}'
    networks:
      - authelia
    restart: unless-stopped
    volumes:
      - authelia-database-data:/var/lib/postgresql/data

  lldap:
    # todo: figure out how to create default authelia user/pwd with lldap_password_manager gruop
    # probably using the lldap bootstrap.sh script as suggested in the readme
    image: docker.io/lldap/lldap:v0.6.1-alpine
    environment:
      - LLDAP_LDAP_BASE_DN=${LLDAP_BASE_DN}
      - LLDAP_LDAP_USER_PASS=${LLDAP_USER_PASS}
      - LLDAP_JWT_SECRET=${LLDAP_JWT_SECRET}
      - LLDAP_KEY_SEED=${LLDAP_KEY_SEED}
      - TZ=${TIMEZONE}
    expose:
      - 3890 # ldap
      # - 6360 # ldaps (ldap over ssl)
      - 17170 # webui
    extends:
      file: common.yml
      service: log-to-json
    networks:
      - ldap
      - proxy
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - lldap-data:/data
