version: "3"

include:
  - atuin.yml
  - forgejo.yml
  - frigate.yml
  - gotify.yml
  - homeassistant.yml
  - immich.yml
  - jellyfin.yml
  - metrics.yml
  - navidrome.yml
  - paperless.yml
  - qbittorrent.yml
  - sabnzbd.yml
  - searxng.yml
  - servarr.yml
  - vaultwarden.yml

networks:
  cloudflared:
  monitor:
  proxy:

volumes:
  caddy-config:

services:
  caddy:
    image: docker.io/hotio/caddy:release-2.8.4
    environment:
      - PROXY_CF_API_EMAIL=${PROXY_CF_API_EMAIL}
      - PROXY_CF_API_TOKEN=${PROXY_CF_API_TOKEN}
      - PROXY_PUBLIC_DOMAIN=${PROXY_PUBLIC_DOMAIN}
      - PROXY_PRIVATE_DOMAIN=${PROXY_PRIVATE_DOMAIN}
    extends:
      file: common.yml
      service: hotio
    networks:
      - proxy
      - cloudflared
    ports:
      - 80:80
      - 443:443/tcp
      - 443:443/udp
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - caddy-config:/config
      - ./caddy/Caddyfile:/config/Caddyfile

  cloudflared:
    image: docker.io/cloudflare/cloudflared:2024.6.0
    command: tunnel --no-autoupdate run --token ${PROXY_CF_TUNNEL_TOKEN}
    extra_hosts:
      - host.docker.internal:host-gateway
    # expose:
    #   - 4506 # metrics
    extends:
      file: common.yml
      service: log-to-json
    networks:
      - cloudflared
      # - monitor
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
