networks:
  # todo: maybe a separate notify network is better than re-using monitor
  monitor:
  proxy:

volumes:
  diun-data:
  gotify-data:

services:
  gotify:
    image: docker.io/gotify/server:2.6.1
    environment:
      - TZ=${TIMEZONE}
    expose:
      - 80 # webui
    extends:
      file: common.yml
      service: log-to-json
    networks:
      - proxy
      - monitor
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - gotify-data:/app/data

  diun:
    image: docker.io/crazymax/diun:4.29
    command: serve
    environment:
      - TZ=${TIMEZONE}
      - DIUN_NOTIF_GOTIFY_ENDPOINT=http://gotify
      - DIUN_NOTIF_GOTIFY_TOKEN=${MONITOR_DIUN_GOTIFY_TOKEN}
      - DIUN_WATCH_WORKERS=10
      - DIUN_WATCH_SCHEDULE=0 */6 * * *
      - DIUN_REGOPTS_0_NAME=docker.io
      - DIUN_REGOPTS_0_SELECTOR=image
      - DIUN_REGOPTS_0_USERNAME=${MONITOR_DIUN_REGOPTS_USERNAME}
      - DIUN_REGOPTS_0_PASSWORD=${MONITOR_DIUN_REGOPTS_PASSWORD}
      - DIUN_PROVIDERS_FILE_FILENAME=/config.yml
    extends:
      file: common.yml
      service: log-to-json
    networks:
      - monitor
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - diun-data:/data
      - ./diun/config.yml:/config.yml:ro
