---
all:
  children:
    box:
      hosts:
        "{{ box_host }}"
      vars:
        ansible_user: root
        ansible_password: root
        ansible_python_interpreter: /usr/bin/python3
        ansible_become_method: doas
        ansible_become_password: "{{ box_password }}"

        box_host: 192.168.56.107
        box_timezone: UTC
        box_hostname: box.local
        box_username: alex
        box_password: alex

