---
all:
  children:
    box:
      hosts:
        192.168.47.128
      vars:
        ansible_user: root
        ansible_python_interpreter: /usr/bin/python3
        ansible_become_method: doas
        # ansible_ssh_private_key_file: "~/.ssh/id_ed25519"

        box_timezone: UTC
        box_hostname: box
        box_username: alex
        box_rootfs: btrfs
        box_rootfs_devices: "/dev/sda /dev/sdb"
        box_ssh_key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIIqQwgcXplAfUV/YeJC8FIpZgl0Hr86P35mj6qcnpEJC alex@picknote.co"

