networks:
  proxy:

volumes:
  jellyfin-config:

services:
  jellyfin:
    image: ghcr.io/hotio/jellyfin:release-10.11.4
    devices:
      - ${JELLYFIN_CARD}:/dev/dri/card0
      - ${JELLYFIN_RENDER}:/dev/dri/renderD128
    expose:
      - 8096 # webui
    group_add:
      - ${JELLYFIN_VIDEO_GROUP}
    extends:
      file: common.yml
      service: hotio
    networks:
      - proxy
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${MEDIA_COLLECTION_PATH}:/data/media/collection
      - jellyfin-config:/config
