networks:
  proxy:

volumes:
  kavita-config:

services:
  kavita:
    image: ghcr.io/kareadita/kavita:0.8.8
    environment:
      - PUID=${MEDIA_PUID}
      - PGID=${MEDIA_PGID}
      - TZ=${TIMEZONE}
    expose:
      - 5000 # webui
    extends:
      file: common.yml
      service: log-to-json
    networks:
      - proxy
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - kavita-config:/kavita/config
      - ${MEDIA_COLLECTION_BOOKS_PATH}:/data/media
