version: "3"

networks:
  monitor:
  proxy:

volumes:
  grafana-config:
  grafana-data:
  prometheus-data:

services:
  grafana:
    image: docker.io/grafana/grafana:10.4.2
    extends:
      file: common.yml
      service: log-to-json
    environment:
      - GF_ANALYTICS_CHECK_FOR_UPDATES=false
      - GF_ANALYTICS_FEEDBACK_LINKS_ENABLED=false
      - GF_ANALYTICS_REPORTING_ENABLED=false
      - GF_DEFAULT_INSTANCE_NAME=selfhosted
      - GF_SECRETSCAN_ENABLED=false
      - GF_SECURITY_ADMIN_PASSWORD=${MONITOR_GRAFANA_SECURITY_ADMIN_PASSWORD}
      - GF_SECURITY_ADMIN_USER=${MONITOR_GRAFANA_SECURITY_ADMIN_USER}
      - GF_SECURITY_COOKIE_SECURE=true
      - GF_SECURITY_COOKIE_SAMESITE=strict
      - GF_SECURITY_DISABLE_GRAVATAR=true
      - GF_SERVER_DOMAIN=grafana.${PROXY_PUBLIC_DOMAIN}
      - GF_SERVER_ROOT_URL=https://grafana.${PROXY_PUBLIC_DOMAIN}
      - GF_USERS_ALLOW_SIGN_UP=false
      - TZ=${TIMEZONE}
    expose:
      - 3000 # webui
    networks:
      - proxy
      - monitor
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - grafana-data:/var/lib/grafana
      - grafana-config:/etc/grafana
      - ./grafana/dashboards:/etc/grafana/provisioning/dashboards
      - ./grafana/datasources:/etc/grafana/provisioning/datasources

  prometheus:
    image: docker.io/prom/prometheus:v2.52.0
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--storage.tsdb.retention.time=30d"
      - "--storage.tsdb.retention.size=10GB"
      - "--web.console.templates=/usr/share/prometheus/consoles"
      - "--web.console.libraries=/usr/share/prometheus/console_libraries"
      - "--web.enable-lifecycle" # reload config on /-/reload POST
    environment:
      - TZ=${TIMEZONE}
    expose:
      - 9090 # metrics
    extra_hosts:
      - host.docker.internal:host-gateway
    extends:
      file: common.yml
      service: log-to-json
    networks:
      - monitor
    restart: unless-stopped
    volumes:
      - prometheus-data:/prometheus
      - ./prometheus/rules:/etc/prometheus/rules
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - /etc/localtime:/etc/localtime:ro

  node-exporter:
    image: docker.io/prom/node-exporter:v1.8.0
    command:
      - "--path.rootfs=/rootfs"
      - "--path.sysfs=/host/sys"
      - "--path.procfs=/host/proc"
      - "--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc|rootfs/var/lib/docker)($$|/)"
      - "--collector.netclass.ignored-devices=^(veth.+|br-.+|docker[0-9])$"
      - "--collector.netdev.device-exclude=^(veth.+|br-.+|docker[0-9])$"
      - "--collector.textfile.directory=/rootfs/home/restic/textfile_collector"
    expose:
      - 9100 # metrics
    extends:
      file: common.yml
      service: log-to-json
    network_mode: host
    pid: host
    restart: unless-stopped
    volumes:
      - /:/rootfs:ro
      - /sys:/host/sys:ro
      - /proc:/host/proc:ro
      - /etc/localtime:/etc/localtime:ro

  smartctl-exporter:
    image: docker.io/prometheuscommunity/smartctl-exporter:v0.12.0
    expose:
      - 9633 # metrics
    extends:
      file: common.yml
      service: log-to-json
    networks:
      - monitor
    privileged: true
    restart: unless-stopped
    user: root

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.49.1
    command:
      - "--port=9250"
      - "--docker_only=true"
      - "--disable_root_cgroup_stats=true"
      - "--enable_metrics=cpu,memory,network"
      - "--store_container_labels=false"
      - "--housekeeping_interval=10s"
      - "--max_housekeeping_interval=15s"
    devices:
      - /dev/kmsg
    environment:
      - CADVISOR_HEALTHCHECK_URL=http://localhost:9250/healthz
    expose:
      - 9250 # metrics
    extends:
      file: common.yml
      service: log-to-json
    networks:
      - monitor
    privileged: true
    restart: unless-stopped
    volumes:
      - /:/rootfs:ro
      - /dev/disk:/dev/disk:ro
      - /sys:/sys:ro
      - /var/lib/docker:/var/lib/docker:ro
      - /var/run:/var/run:ro
      - /etc/localtime:/etc/localtime:ro
