networks:
  proxy:

volumes:
  navidrome-data:

services:
  navidrome:
    image: ghcr.io/navidrome/navidrome:0.59.0
    environment:
      - ND_SCANSCHEDULE=@daily
      - ND_ENABLETRANSCODINGCONFIG=false
      # data collection: https://www.navidrome.org/docs/getting-started/insights/
      - ND_ENABLEINSIGHTSCOLLECTOR=true
      # used to fetch artist images
      - ND_LASTFM_ENABLED=true
      - ND_LASTFM_APIKEY=${NAVIDROME_LASTFM_APIKEY}
      - ND_LASTFM_SECRET=${NAVIDROME_LASTFM_SECRET}
    expose:
      - 4533 # webui
    extends:
      file: common.yml
      service: log-to-json
    networks:
      - proxy
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - navidrome-data:/data
      - ${MEDIA_COLLECTION_MUSIC_PATH}:/music:ro
