networks:
  proxy:
  qbit:

volumes:
  qbit-config:
  qbitmanage-config:

services:
  qbit:
    image: ghcr.io/hotio/qbittorrent:release-5.0.5
    cap_add:
      - NET_ADMIN
    environment:
      - VPN_ENABLED=${MEDIA_TORRENT_VPN_ENABLED}
      - VPN_PROVIDER=${MEDIA_TORRENT_VPN_PROVIDER}
      - VPN_LAN_NETWORK=${MEDIA_TORRENT_VPN_LAN_NETWORK}
      - VPN_CONF=wg0
      - VPN_LAN_LEAK_ENABLED=false
      - VPN_AUTO_PORT_FORWARD=true
      - VPN_HEALTHCHECK_ENABLED=true
    expose:
      - 8080 # webui
    extends:
      file: common.yml
      service: hotio
    networks:
      - proxy
      - qbit
    restart: unless-stopped
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv6.conf.all.disable_ipv6=1
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - qbit-config:/config
      - ./qbittorrent/wg0.conf:/config/wireguard/wg0.conf
      - ${MEDIA_DOWNLOADS_TORRENT_PATH}:/data/media/downloads/torrent

  qbitmanage:
    image: ghcr.io/hotio/qbitmanage:release-4.6.5
    extends:
      file: common.yml
      service: hotio
    networks:
      - qbit
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - qbitmanage-config:/config
      - ./qbittorrent/qbitmanage.yml:/config/config.yml
      - ${MEDIA_DOWNLOADS_TORRENT_PATH}:/data/media/downloads/torrent
