version: "3"

networks:
  proxy:

volumes:
  sabnzbd-config:

services:
  sabnzbd:
    image: docker.io/hotio/sabnzbd:release-4.2.2
    environment:
      - PUID=${MEDIA_PUID}
      - PGID=${MEDIA_PGID}
      - UMASK=${MEDIA_UMASK}
      - TZ=${TIMEZONE}
    expose:
      - 8080 # webui
    extends:
      file: common.yml
      service: log-to-json
    networks:
      - proxy
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - sabnzbd-config:/config
      - ${MEDIA_DOWNLOADS_USENET_PATH}:/data/media/downloads/usenet
