networks:
  proxy:
  searxng:

volumes:
  searxng-redis-data:

services:
  searxng:
    image: ghcr.io/searxng/searxng:2025.7.25-83adda8
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
    environment:
      - SEARXNG_SECRET=${SEARXNG_SECRET}
      - SEARXNG_BASE_URL=https://search.${PROXY_PUBLIC_DOMAIN}
      - SEARXNG_REDIS_URL=redis://searxng-redis:6379
      - TZ=${TIMEZONE}
    expose:
      - 8080 # webui
    extends:
      file: common.yml
      service: log-to-json
    networks:
      - proxy
      - searxng
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./searxng/settings.yml:/etc/searxng/settings.yml:ro
      - ./searxng/limiter.toml:/etc/searxng/limiter.toml:ro
      # todo: change favicons
      # https://github.com/searxng/searxng-docker/discussions/57#discussioncomment-2597013

  searxng-redis:
    image: docker.io/valkey/valkey:7-alpine
    command: --save 30 1 --loglevel warning
    cap_drop:
      - ALL
    cap_add:
      - SETGID
      - SETUID
      - DAC_OVERRIDE
    expose:
      - 6379 # api
    extends:
      file: common.yml
      service: log-to-json
    healthcheck:
      test: redis-cli ping
    networks:
      - searxng
    restart: unless-stopped
    volumes:
      - searxng-redis-data:/data
