networks:
  proxy:
  monitor:

volumes:
  jellyseerr-config:
  lidarr-config:
  prowlarr-config:
  radarr-config:
  recyclarr-config:
  sonarr-config:

services:
  jellyseerr:
    image: docker.io/hotio/jellyseerr:release-2.2.3
    expose:
      - 5055 # webui
    extends:
      file: common.yml
      service: hotio
    networks:
      - proxy
      - monitor
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - jellyseerr-config:/app/config

  lidarr:
    image: docker.io/hotio/lidarr:release-2.8.2.4493
    expose:
      - 8686 # webui
    extends:
      file: common.yml
      service: hotio
    networks:
      - proxy
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - lidarr-config:/config
      - ${MEDIA_ROOT_PATH}:/data/media

  prowlarr:
    image: docker.io/hotio/prowlarr:release-1.29.2.4915
    expose:
      - 9696 # webui
    extends:
      file: common.yml
      service: hotio
    networks:
      - proxy
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${MEDIA_ROOT_PATH}:/data/media
      - prowlarr-config:/config

  radarr:
    image: docker.io/hotio/radarr:release-5.17.2.9580
    expose:
      - 7878 # webui
    extends:
      file: common.yml
      service: hotio
    networks:
      - proxy
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${MEDIA_ROOT_PATH}:/data/media
      - radarr-config:/config

  recyclarr:
    image: docker.io/recyclarr/recyclarr:7.4.0
    environment:
      - TZ=${TIMEZONE}
    extends:
      file: common.yml
      service: log-to-json
    networks:
      - proxy
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - recyclarr-config:/config
      - ./recyclarr/recyclarr.yml:/config/recyclarr.yml

  sonarr:
    image: docker.io/hotio/sonarr:release-4.0.12.2823
    expose:
      - 8989 # webui
    extends:
      file: common.yml
      service: hotio
    networks:
      - proxy
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${MEDIA_ROOT_PATH}:/data/media
      - sonarr-config:/config
