version: "3"

networks:
  proxy:
  monitor:

volumes:
  jellyseerr-config:
  lidarr-config:
  prowlarr-config:
  radarr-config:
  recyclarr-config:
  sonarr-config:

services:
  jellyseerr:
    image: docker.io/hotio/jellyseerr:release-1.9.2
    expose:
      - 5055 # webui
    extends:
      file: common.yml
      service: hotio
    networks:
      - proxy
      - monitor
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - jellyseerr-config:/app/config

  lidarr:
    image: docker.io/hotio/lidarr:release-2.5.3.4341
    expose:
      - 8686 # webui
    extends:
      file: common.yml
      service: hotio
    networks:
      - proxy
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - lidarr-config:/config
      - ${MEDIA_ROOT_PATH}:/data/media

  prowlarr:
    image: docker.io/hotio/prowlarr:release-1.24.3.4754
    expose:
      - 9696 # webui
    extends:
      file: common.yml
      service: hotio
    networks:
      - proxy
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${MEDIA_ROOT_PATH}:/data/media
      - prowlarr-config:/config

  radarr:
    image: docker.io/hotio/radarr:release-5.11.0.9244
    expose:
      - 7878 # webui
    extends:
      file: common.yml
      service: hotio
    networks:
      - proxy
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${MEDIA_ROOT_PATH}:/data/media
      - radarr-config:/config

  recyclarr:
    image: docker.io/recyclarr/recyclarr:7.2.4
    environment:
      - TZ=${TIMEZONE}
    extends:
      file: common.yml
      service: log-to-json
    networks:
      - proxy
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - recyclarr-config:/config
      - ./recyclarr/recyclarr.yml:/config/recyclarr.yml

  sonarr:
    image: docker.io/hotio/sonarr:release-4.0.9.2244
    expose:
      - 8989 # webui
    extends:
      file: common.yml
      service: hotio
    networks:
      - proxy
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${MEDIA_ROOT_PATH}:/data/media
      - sonarr-config:/config
