version: "3"

networks:
  proxy:
  monitor:

volumes:
  jellyseerr-config:
  lidarr-config:
  prowlarr-config:
  radarr-config:
  recyclarr-config:
  sonarr-config:

x-hotio: &environment-hotio
  environment:
    - PUID=${MEDIA_PUID}
    - PGID=${MEDIA_PGID}
    - UMASK=${MEDIA_UMASK}
    - TZ=${TIMEZONE}

services:
  jellyseerr:
    image: docker.io/hotio/jellyseerr:release-1.7.0
    <<: *environment-hotio
    expose:
      - 5055 # webui
    extends:
      file: common.yml
      service: log-to-json
    networks:
      - proxy
      - monitor
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - jellyseerr-config:/app/config

  lidarr:
    image: docker.io/hotio/lidarr:release-2.1.7.4030
    <<: *environment-hotio
    expose:
      - 8686 # webui
    extends:
      file: common.yml
      service: log-to-json
    networks:
      - proxy
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - lidarr-config:/config
      - ${MEDIA_ROOT_PATH}:/data/media

  prowlarr:
    image: docker.io/hotio/prowlarr:release-1.13.3.4273
    <<: *environment-hotio
    expose:
      - 9696 # webui
    extends:
      file: common.yml
      service: log-to-json
    networks:
      - proxy
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${MEDIA_ROOT_PATH}:/data/media
      - prowlarr-config:/config

  radarr:
    image: docker.io/hotio/radarr:release-5.3.6.8612
    <<: *environment-hotio
    expose:
      - 7878 # webui
    extends:
      file: common.yml
      service: log-to-json
    networks:
      - proxy
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${MEDIA_ROOT_PATH}:/data/media
      - radarr-config:/config

  recyclarr:
    image: docker.io/recyclarr/recyclarr:6.0.2
    environment:
      - TZ=${TIMEZONE}
    extends:
      file: common.yml
      service: log-to-json
    networks:
      - proxy
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - recyclarr-config:/config
      - ./recyclarr/recyclarr.yml:/config/recyclarr.yml

  sonarr:
    image: docker.io/hotio/sonarr:release-4.0.2.1183
    <<: *environment-hotio
    expose:
      - 8989 # webui
    extends:
      file: common.yml
      service: log-to-json
    networks:
      - proxy
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${MEDIA_ROOT_PATH}:/data/media
      - sonarr-config:/config
