networks:
  proxy:
  monitor:

volumes:
  jellyseerr-config:
  lidarr-config:
  prowlarr-config:
  radarr-config:
  recyclarr-config:
  sonarr-config:

services:
  jellyseerr:
    image: ghcr.io/hotio/jellyseerr:release-2.7.3
    expose:
      - 5055 # webui
    extends:
      file: common.yml
      service: hotio
    networks:
      - proxy
      - monitor
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - jellyseerr-config:/app/config

  lidarr:
    image: ghcr.io/hotio/lidarr:pr-plugins-3.1.1.4901
    expose:
      - 8686 # webui
    extends:
      file: common.yml
      service: hotio
    networks:
      - proxy
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - lidarr-config:/config
      - ${MEDIA_ROOT_PATH}:/data/media

  prowlarr:
    image: ghcr.io/hotio/prowlarr:release-2.3.0.5236
    expose:
      - 9696 # webui
    extends:
      file: common.yml
      service: hotio
    networks:
      - proxy
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${MEDIA_ROOT_PATH}:/data/media
      - prowlarr-config:/config

  radarr:
    image: ghcr.io/hotio/radarr:release-6.0.4.10291
    expose:
      - 7878 # webui
    extends:
      file: common.yml
      service: hotio
    networks:
      - proxy
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${MEDIA_ROOT_PATH}:/data/media
      - radarr-config:/config

  recyclarr:
    image: ghcr.io/recyclarr/recyclarr:7.5.2
    environment:
      - TZ=${TIMEZONE}
    extends:
      file: common.yml
      service: log-to-json
    networks:
      - proxy
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - recyclarr-config:/config
      - ./recyclarr/recyclarr.yml:/config/recyclarr.yml

  sonarr:
    image: ghcr.io/hotio/sonarr:release-4.0.16.2944
    expose:
      - 8989 # webui
    extends:
      file: common.yml
      service: hotio
    networks:
      - proxy
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${MEDIA_ROOT_PATH}:/data/media
      - sonarr-config:/config
