---
- name: setup alpine linux
  hosts: box
  vars:
    box_timezone: "UTC"
    box_root_fs: "btrfs"
    box_root_mount: "/mnt"
    box_net_iface: "eth0"

  tasks:
    - name: copy setup-apline template
      template:
        src: files/setup-alpine.j2
        dest: /root/setup-alpine.txt

    - name: run setup-alpine with template
      shell:
        cmd: "yes | setup-alpine -e -f /root/setup-alpine.txt"

    - name: reboot
      reboot:

    - name: copy fstab
      template:
        src: files/etc/fstab
        dest: /etc/fstab

    - name: copy apk repositories config
      template:
        src: files/etc/apk/repositories
        dest: /etc/apk/repositories
