networks:
  proxy:
  frp:

volumes:
  slskd-data:

services:
  slskd:
    image: ghcr.io/slskd/slskd:0.25.1
    environment:
      - SLSKD_NO_AUTH=true
      - SLSKD_NO_HTTPS=true
      - SLSKD_REMOTE_CONFIGURATION=false
      - SLSKD_HTTP_PORT=5030
      - SLSKD_SLSK_LISTEN_PORT=50300
      # use a socks5 proxy so the incoming connections go through FRP
      # instead of peers trying to connect to the server IP
      - SLSKD_SLSK_PROXY_ENABLED=true
      - SLSKD_SLSK_PROXY_ADDRESS=frp.${PROXY_PUBLIC_DOMAIN}
      - SLSKD_SLSK_PROXY_PORT=41080
      - SLSKD_SLSK_PROXY_USERNAME=${SLSKD_SLSK_PROXY_USERNAME}
      - SLSKD_SLSK_PROXY_PASSWORD=${SLSKD_SLSK_PROXY_PASSWORD}
      - SLSKD_SLSK_USERNAME=${MEDIA_SLSKD_USERNAME}
      - SLSKD_SLSK_PASSWORD=${MEDIA_SLSKD_PASSWORD}
      # these subdirectories must exists under MEDIA_DOWNLOADS_SOULSEEK_PATH/
      - SLSKD_DOWNLOADS_DIR=/data/media/downloads/soulseek/downloads
      - SLSKD_INCOMPLETE_DIR=/data/media/downloads/soulseek/incomplete
      # uncomment the next line and the corresponding volume mount to enable sharing
      - SLSKD_SHARED_DIR=/data/media/collection
      - SLSKD_UMASK=${MEDIA_UMASK}
      - TZ=${TIMEZONE}
    expose:
      - 5030 # slskd webui
      - 50300 # incoming connections
    extends:
      file: common.yml
      service: log-to-json
    networks:
      - proxy
      - frp
    restart: unless-stopped
    user: ${MEDIA_PUID}:${MEDIA_PGID}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${MEDIA_COLLECTION_MUSIC_PATH}:/data/media/collection/music
      - ${MEDIA_DOWNLOADS_SOULSEEK_PATH}:/data/media/downloads/soulseek
      - slskd-data:/app
