networks:
  proxy:

volumes:
  slskd-data:
  slskd-gluetun:

services:
  slskd:
    image: ghcr.io/slskd/slskd:0.24.3
    environment:
      - SLSKD_NO_AUTH=true
      - SLSKD_NO_HTTPS=true
      - SLSKD_REMOTE_CONFIGURATION=false
      - SLSKD_SLSK_USERNAME=${MEDIA_SLSKD_USERNAME}
      - SLSKD_SLSK_PASSWORD=${MEDIA_SLSKD_PASSWORD}
      # these subdirectories must exists under MEDIA_DOWNLOADS_SOULSEEK_PATH/
      - SLSKD_DOWNLOADS_DIR=/data/media/downloads/soulseek/downloads
      - SLSKD_INCOMPLETE_DIR=/data/media/downloads/soulseek/incomplete
      # uncomment the next line and the corresponding volume mount to enable sharing
      - SLSKD_SHARED_DIR=/data/media/collection
      - SLSKD_UMASK=${MEDIA_UMASK}
      - TZ=${TIMEZONE}
    extends:
      file: common.yml
      service: log-to-json
    network_mode: "service:slskd-gluetun"
    restart: unless-stopped
    user: ${MEDIA_PUID}:${MEDIA_PGID}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${MEDIA_COLLECTION_MUSIC_PATH}:/data/media/collection/music
      - ${MEDIA_DOWNLOADS_SOULSEEK_PATH}:/data/media/downloads/soulseek
      - slskd-data:/app

  slskd-gluetun:
    image: docker.io/qmcgaw/gluetun:v3.41.1
    cap_add:
      - NET_ADMIN
    environment:
      - VPN_TYPE=wireguard
      - VPN_SERVICE_PROVIDER=${GLUETUN_VPN_SERVICE_PROVIDER}
      - VPN_PORT_FORWARDING=on
      # automatically update listen port in slskd, changes are picked up immediately
      - VPN_PORT_FORWARDING_UP_COMMAND="sed -i 's/listen_port:.*/listen_port\:\ {{PORTS}}/' /app/slskd.yml"
      - HTTP_CONTROL_SERVER=on
      - SERVER_HOSTNAMES=${GLUETUN_SERVER_HOSTNAMES}
      - WIREGUARD_PRIVATE_KEY=${GLUETUN_WIREGUARD_PRIVATE_KEY}
      - TZ=${TIMEZONE}
    expose:
      - 5030 # slskd webui
      - 8000 # gluetun control server
    extends:
      file: common.yml
      service: log-to-json
    networks:
      - proxy
    restart: unless-stopped
    volumes:
      - slskd-data:/app
      - slskd-gluetun:/gluetun
