networks:
  proxy:
  snikket:

volumes:
  snikket-data:
  snikket-acme-challenges:

# see: https://github.com/snikket-im/snikket-server
# see: https://snikket.org/service/help/advanced/firewall/
# see: https://snikket.org/service/help/advanced/reverse_proxy/

services:
  snikket:
    image: docker.io/snikket/snikket-server:stable.20260611
    environment:
      - SNIKKET_DOMAIN=chat.${PROXY_PUBLIC_DOMAIN}
      - SNIKKET_ADMIN_EMAIL=admin@${PROXY_PUBLIC_DOMAIN}
      - SNIKKET_SITE_NAME=Sneaky Parakeet
      - SNIKKET_TWEAK_INTERNAL_HTTP_INTERFACE=0.0.0.0
      - SNIKKET_TWEAK_INTERNAL_HTTP_PORT=5280
      - SNIKKET_TWEAK_STORAGE=sqlite
      - SNIKKET_TWEAK_TURNSERVER_MIN_PORT=60000
      - SNIKKET_TWEAK_TURNSERVER_MAX_PORT=60010
      # disable support for legacy SASL, requiring all clients to support SASL2
      # increases security and speed, but a lot of clients do not have SASL2 support
      # - SNIKKET_TWEAK_REQUIRE_SASL2=1
      - SNIKKET_UPDATE_CHECK=0
    extends:
      file: common.yml
      service: log-to-json
    expose:
      - 5280/tcp # internal apis where caddy should point to
      - 5222/tcp # client to server connection (XMPP c2s)
      - 5269/tcp # federation with other servers (XMPP s2s)
      - 5000/tcp # file transfer proxy (proxy65)
      - 3478/tcp # AV negotiation and discovery proxy (STUN/TURN)
      - 3478/udp
      - 3479/tcp
      - 3479/udp
      - 5349/tcp # AV negotiation and discovery proxy over TLS (STUNS/TURNS)
      - 5349/udp
      - 5350/tcp
      - 5350/udp
      - 60000/udp # AV data proxy (TURN data)
      - 60001/udp
      - 60002/udp
      - 60003/udp
      - 60004/udp
      - 60005/udp
      - 60006/udp
      - 60007/udp
      - 60008/udp
      - 60009/udp
      - 60010/udp # compose syntax does not support port ranges for expose :(
    healthcheck:
      test: prosodyctl status
      start_period: 10s
    networks:
      - snikket
      - proxy
      - frp
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - snikket-data:/snikket

  snikket-certs:
    image: snikket/snikket-cert-manager:stable.20260611
    environment:
      - SNIKKET_DOMAIN=chat.${PROXY_PUBLIC_DOMAIN}
      - SNIKKET_ADMIN_EMAIL=admin@${PROXY_PUBLIC_DOMAIN}
    extends:
      file: common.yml
      service: log-to-json
    networks:
      - snikket
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - snikket-data:/snikket
      - snikket-acme-challenges:/var/www/.well-known/acme-challenge

  snikket-web:
    image: docker.io/snikket/snikket-web-portal:stable.20260611
    depends_on:
      snikket:
        condition: service_healthy
    environment:
      - SNIKKET_DOMAIN=chat.${PROXY_PUBLIC_DOMAIN}
      - SNIKKET_SITE_NAME=Sneaky Parakeet
      - SNIKKET_TWEAK_PORTAL_INTERNAL_HTTP_INTERFACE=0.0.0.0
      - SNIKKET_TWEAK_PORTAL_INTERNAL_HTTP_PORT=5765
      # should point to the same port as SNIKKET_TWEAK_INTERNAL_HTTP_PORT
      - SNIKKET_WEB_PROSODY_ENDPOINT=http://snikket:5280
    extends:
      file: common.yml
      service: log-to-json
    expose:
      - 5765/tcp # webui
    healthcheck:
      test:
        [
          "CMD",
          "python3",
          "-c",
          "import urllib.request; urllib.request.urlopen('http://localhost:5765/_health')",
        ]
      start_period: 10s
    networks:
      - snikket
      - proxy
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
