networks:
  proxy:
  syncstorage:

volumes:
  syncstorage-database-data:

services:
  syncstorage:
    image: ghcr.io/mozilla-services/syncstorage-rs/syncserver-postgres:0.23.3
    depends_on:
      syncstorage-database:
        condition: service_healthy
    environment:
      - RUST_LOG=info
      - SYNC_HOST=0.0.0.0
      - SYNC_PORT=8000
      - SYNC_HUMAN_LOGS=true
      - SYNC_MASTER_SECRET=${SYNCSTORAGE_MASTER_SECRET}
      - SYNC_SYNCSTORAGE__DATABASE_URL=postgres://${SYNCSTORAGE_DB_USERNAME}:${SYNCSTORAGE_DB_PASSWORD}@syncstorage-database:5432/${SYNCSTORAGE_DB_DATABASE_NAME}
      - SYNC_TOKENSERVER__DATABASE_URL=postgres://${SYNCSTORAGE_DB_USERNAME}:${SYNCSTORAGE_DB_PASSWORD}@syncstorage-database:5432/${SYNCSTORAGE_DB_DATABASE_NAME}
      - SYNC_TOKENSERVER__ENABLED=true
      - SYNC_TOKENSERVER__RUN_MIGRATIONS=true
      - SYNC_TOKENSERVER__NODE_TYPE=postgres
      - SYNC_TOKENSERVER__FXA_EMAIL_DOMAIN=api.accounts.firefox.com
      - SYNC_TOKENSERVER__FXA_OAUTH_SERVER_URL=https://oauth.accounts.firefox.com
      - SYNC_TOKENSERVER__FXA_METRICS_HASH_SECRET=${SYNCSTORAGE_METRICS_HASH_SECRET}
      - SYNC_TOKENSERVER__INIT_NODE_URL=https://ffs.${PROXY_PUBLIC_DOMAIN}
      - TZ=${TIMEZONE}
    expose:
      - 8000 # api
    extends:
      file: common.yml
      service: log-to-json
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/__heartbeat__"]
      interval: 300s
      timeout: 10s
      retries: 3
      start_period: 60s
    networks:
      - proxy
      - syncstorage
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro

  syncstorage-database:
    image: docker.io/postgres:18-alpine
    environment:
      - POSTGRES_USER=${SYNCSTORAGE_DB_USERNAME}
      - POSTGRES_PASSWORD=${SYNCSTORAGE_DB_PASSWORD}
      - POSTGRES_DB=${SYNCSTORAGE_DB_DATABASE_NAME}
    expose:
      - 5432 # db
    extends:
      file: common.yml
      service: log-to-json
    healthcheck:
      test: pg_isready --dbname='${SYNCSTORAGE_DB_DATABASE_NAME}' --username='${SYNCSTORAGE_DB_USERNAME}'
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - syncstorage
    restart: unless-stopped
    volumes:
      - syncstorage-database-data:/var/lib/postgresql
