networks:
  proxy:

volumes:
  wakapi-data:

services:
  wakapi:
    image: ghcr.io/muety/wakapi:2.17.1
    expose:
      - 3000 # api
    environment:
      - WAKAPI_PUBLIC_URL=https://waka.${PROXY_PUBLIC_DOMAIN}
      - WAKAPI_PASSWORD_SALT=${WAKAPI_PASSWORD_SALT}
      - WAKAPI_INSECURE_COOKIES=false
      - WAKAPI_ALLOW_SIGNUP=false
      - WAKAPI_DISABLE_FRONTPAGE=true
      # note: will be available in the upcoming releases
      # see https://github.com/muety/wakapi/commit/fcaa8a2056d88795e9a56a621746135b98ec5498
      # - WAKAPI_OIDC_ALLOW_SIGNUP=false
      - WAKAPI_OIDC_PROVIDERS_0_NAME=authelia
      - WAKAPI_OIDC_PROVIDERS_0_DISPLAY_NAME=Authelia
      - WAKAPI_OIDC_PROVIDERS_0_CLIENT_ID=${AUTH_WAKAPI_CLIENT_ID}
      - WAKAPI_OIDC_PROVIDERS_0_CLIENT_SECRET=${AUTH_WAKAPI_CLIENT_SECRET}
      - WAKAPI_OIDC_PROVIDERS_0_ENDPOINT=https://auth.${PROXY_PUBLIC_DOMAIN}
      - TZ=${TIMEZONE}
    extends:
      file: common.yml
      service: log-to-json
    networks:
      - proxy
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - wakapi-data:/data
