---
apiVersion: v1
kind: ConfigMap
metadata:
  name: hotio-config
data:
  PUID: "1000"
  PGID: "1000"
  UMASK: "002"
  TZ: "UTC"
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: vpn
  name: vpn
spec:
  restartPolicy: Always
  containers:
    - name: qbit
      image: docker.io/hotio/qbittorrent:release-4.4.5
      resources: {}
      securityContext:
        capabilities:
          add:
            - NET_RAW
            - NET_ADMIN
            - SYS_MODULE
      env:
        - name: VPN_ENABLED
          value: "true"
        - name: VPN_IP_CHECK_DELAY
          value: "10"
        - name: VPN_IP_CHECK_EXIT
          value: "false"
        - name: VPN_LAN_NETWORK
          value: "10.10.0.0/24"
      envFrom:
        - configMapRef:
            name: hotio-config
            optional: false
      volumeMounts:
        - name: localtime
          mountPath: /etc/localtime
        - name: qbittorrent-config
          mountPath: /config
        - name: qbittorrent-wireguard
          mountPath: /config/wireguard/wg0.conf
        - name: downloads-torrent
          mountPath: /data/media/downloads/torrent

  volumes:
    - name: localtime
      hostPath:
        path: /etc/localtime
        readOnly: true
        type: File
    - name: downloads-torrent
      hostPath:
        path: /mnt/pool/storage/media/downloads/torrent
        type: Directory

    - name: qbittorrent-config
      persistentVolumeClaim:
        claimName: qbittorrent-config
    - name: qbittorrent-wireguard
      hostPath:
        path: /home/alex/pods/media/qbittorrent/wg0.conf
        readOnly: true
        type: File