---
- name: update apk repsitories
  community.general.apk:
    update_cache: true

- name: install and configure doas
  community.general.apk:
    name: doas

- name: install and configure docker
  community.general.apk:
    name: docker

- name: install and configure libvirt and qemu
  community.general.apk:
    name: qemu-img,qemu-system-x86_64,libvirt-qemu

- name: install and configure libvirt and qemu
  community.general.apk:
    name: qemu-img,qemu-system-x86_64,libvirt-qemu

- name: install and configure mergerfs and snapraid
  community.general.apk:
    name: mergerfs@edge-testing,snapraid@edge-testing