authentication_backend:
  # password reset through authelia works normally
  password_reset:
    disable: false

  # how often to check if there is an user update in ldap
  refresh_interval: 1m

  ldap:
    implementation: custom
    timeout: 5s
    start_tls: false
    # set this to ou=people, all users are stores in this ou
    additional_users_dn: ou=people
    # to allow sign in both with username and email, use this filter
    # (&(|({username_attribute}={input})({mail_attribute}={input}))(objectClass=person))
    users_filter: "(&({username_attribute}={input})(objectClass=person))"
    # set this to ou=groups, all groups are stored in this ou
    additional_groups_dn: ou=groups
    groups_filter: "(member={dn})"
    # attributes holding the name of the group
    attributes:
      display_name: displayName
      username: uid
      group_name: cn
      mail: mail

    # "user" should be the username you created for authentication with the "lldap_strict_readonly" permission.
    # if configuring Authelia to change user passwords, then this user needs the "lldap_password_manager" permission
    # user: see authelia.yml
    # password: see authelia.yml

access_control:
  default_policy: two_factor

session:
  cookies:
    - domain: '{{ mustEnv "PROXY_PUBLIC_DOMAIN" }}'
      authelia_url: https://auth.{{ mustEnv "PROXY_PUBLIC_DOMAIN" }}
      # default_redirection_url: https://home.{{ mustEnv "PROXY_REDIRECT_TO" }}
