# yaml-language-server: $schema=https://creativeprojects.github.io/resticprofile/jsonschema/config-2.json
version: "2"

mixins:
  stop-start-container:
    default-vars:
      container: none

    run-before: docker compose -p box stop $container
    run-finally: docker compose -p box start $container
