apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base
- pod.yml

configMapGenerator:
  - name: proxy-config
    envs: 
      - .env

generatorOptions:
  disableNameSuffixHash: true

replacements:
  - source:
      kind: ConfigMap
      name: proxy-config
      fieldPath: data.PROXY_CADDY_CONFIG_FILE
    targets:
      - select:
          kind: Pod
          name: proxy
        fieldPaths:
          - spec.volumes.[name=caddy-config-file].hostPath.path

  - source:
      kind: ConfigMap
      name: proxy-config
      fieldPath: data.PROXY_BLOCKY_CONFIG_FILE
    targets:
      - select:
          kind: Pod
          name: proxy
        fieldPaths:
          - spec.volumes.[name=blocky-config-file].hostPath.path
