bindPort = 7000
tcpmuxHTTPConnectPort = 3912

allowPorts = [
  { single = 22 },
  { single = 80 },
  { single = 443 },
  # { start = 2000, end = 3000 },
]

auth.token = "{{ .Envs.PROXY_FRP_AUTH_TOKEN }}"

# admin dashboard
# webServer.addr = "0.0.0.0"
# webServer.port = 7500
# webServer.user = "admin"
# webServer.password = "admin"
