# yaml-language-server: $schema=https://creativeprojects.github.io/resticprofile/jsonschema/config-1.json
version: "1"

includes:
  - conf.d/*.yaml
  - profiles.d/*.yaml

global:
  scheduler: crond

groups:
  full:
    - immich
    - paperless

immich:
  inherit: default

  # run-before: echo "Starting"
  # run-after: echo "Finishing"
  # run-after-fail: echo "Finishing"

  backup:
    schedule: "03:00"
    check-before: true
    # schedule-permission: system

    source:
      - /mnt/pool/immich
    tag:
      - "private"

  forget:
    keep-within: "7d"
