---
- name: update packages
  apk:
    update_cache: true

- name: install hardware management tools
  apk:
    name: e2fsprogs-extra,pciutils,smartmontools,nvme-cli,iotop

- name: bash
  apk:
    name: bash,bash-completion

- name: install cli tools
  apk:
    name: file,neovim,zellij@edge,bat,ripgrep,fd,lsd,zoxide,skim,ouch@edge,starship

- name: install container tools
  apk:
    name: podman@edge,kustomize@edge,runuser