# yaml-language-server: $schema=https://creativeprojects.github.io/resticprofile/jsonschema/config-2.json
version: "2"

includes:
  - conf.d/*.yaml
  - profiles.d/*.yaml

global:
  default-command: profiles
  scheduler: crond
  # scheduler: crontab:-:/etc/crontabs/restic
  # http notification request timeout
  send-timeout: 5s

groups:
  private:
    profiles:
      - atuin-database
      - forgejo
      - forgejo-database
      - frigate
      - immich
      - jellyfin
      - navidrome
      - paperless
      - paperless-database
      - vaultwarden
  tools:
    profiles:
      - authelia-database
      - caddy
      - gotify
      - grafana
      - homeassistant
      - slskd
      - wakapi
  servarr:
    profiles:
      - radarr
      - sonarr
      - lidarr
      - prowlarr
      - jellyseerr
      - qbit
      - nzb
