- name: docker.io/caddy
  watch_repo: true
  max_tags: 3
  sort_tags: semver
  notify_on:
    - new
  include_tags:
    - ^\d+\.\d+\.\d+-alpine$

- name: docker.io/spx01/blocky
  watch_repo: true
  max_tags: 3
  sort_tags: semver
  notify_on:
    - new
  include_tags:
    - ^v\d+\.\d+$

- name: docker.io/cloudflare/cloudflared
  watch_repo: true
  max_tags: 3
  sort_tags: semver
  notify_on:
    - new
  include_tags:
    - ^\d+\.\d+\.\d+$

- name: docker.io/hotio/jellyfin
  watch_repo: true
  max_tags: 3
  sort_tags: semver
  notify_on:
    - new
  include_tags:
    - ^release-\d+\.\d+\.\d+-\d+$

- name: docker.io/fallenbagel/jellyseerr
  watch_repo: true
  max_tags: 3
  sort_tags: semver
  notify_on:
    - new
  include_tags:
    - ^\d+\.\d+\.\d+$

- name: docker.io/hotio/radarr
  watch_repo: true
  max_tags: 3
  sort_tags: semver
  notify_on:
    - new
  include_tags:
    - ^release-\d+\.\d+\.\d+\.\d+$

- name: docker.io/hotio/sonarr
  watch_repo: true
  max_tags: 3
  sort_tags: semver
  notify_on:
    - new
  include_tags:
    - ^v4-\d+\.\d+\.\d+\.\d+$

- name: docker.io/hotio/prowlarr
  watch_repo: true
  max_tags: 3
  sort_tags: semver
  notify_on:
    - new
  include_tags:
    - ^release-\d+\.\d+\.\d+\.\d+$

- name: docker.io/recyclarr/recyclarr
  watch_repo: true
  max_tags: 3
  sort_tags: semver
  notify_on:
    - new
  include_tags:
    - ^\d+\.\d+\.\d+$

- name: docker.io/deluan/navidrome
  watch_repo: true
  max_tags: 3
  sort_tags: semver
  notify_on:
    - new
  include_tags:
    - ^\d+\.\d+\.\d+$

- name: docker.io/hotio/lidarr
  watch_repo: true
  max_tags: 3
  sort_tags: semver
  notify_on:
    - new
  include_tags:
    - ^release-\d+\.\d+\.\d+\.\d+$

- name: docker.io/linuxserver/calibre-web
  watch_repo: true
  max_tags: 3
  sort_tags: semver
  notify_on:
    - new
  include_tags:
    - ^\d+\.\d+\.\d+$

- name: docker.io/hotio/readarr
  watch_repo: true
  max_tags: 3
  sort_tags: semver
  notify_on:
    - new
  include_tags:
    - ^testing-\d+\.\d+\.\d+\.\d+$

- name: docker.io/hotio/sabnzbd
  watch_repo: true
  max_tags: 3
  sort_tags: semver
  notify_on:
    - new
  include_tags:
    - ^release-\d+\.\d+\.\d+$

- name: docker.io/hotio/qbittorrent:release
  notify_on:
    - update

- name: docker.io/hotio/qbitmanage:release
  notify_on:
    - update

- name: docker.io/altran1502/immich-server:release
  notify_on:
    - update

- name: docker.io/vaultwarden/server
  watch_repo: true
  max_tags: 3
  sort_tags: semver
  notify_on:
    - new
  include_tags:
    - ^\d+\.\d+\.\d+-alpine$

- name: docker.io/gotify/server
  watch_repo: true
  max_tags: 3
  sort_tags: semver
  notify_on:
    - new
  include_tags:
    - ^\d+\.\d+\.\d+$

- name: docker.io/crazymax/diun
  watch_repo: true
  max_tags: 3
  sort_tags: semver
  notify_on:
    - new
  include_tags:
    - ^\d+\.\d+\.\d+$

- name: docker.io/grafana/grafana
  watch_repo: true
  max_tags: 3
  sort_tags: semver
  notify_on:
    - new
  include_tags:
    - ^\d+\.\d+\.\d+$

- name: docker.io/prom/prometheus
  watch_repo: true
  max_tags: 3
  sort_tags: semver
  notify_on:
    - new
  include_tags:
    - ^v\d+\.\d+\.\d+$

- name: docker.io/paperlessngx/paperless-ngx
  watch_repo: true
  max_tags: 3
  sort_tags: semver
  notify_on:
    - new
  include_tags:
    - ^\d+\.\d+\.\d+$

