---
- name: setup box filesystem
  hosts: box
  vars:
    pool_name: "pool"

    pool_devices:
      - device: sda
      - device: sdb
      - device: sdc
      - device: sdd
      - device: sde

    cache_devices:
      - device: nvme0n1p1

    all_devices: "{{ pool_devices + cache_devices }}"

  tasks:
    - name: ensure devices exist on the host
      fail:
        msg: "Device doesn't exist"
      when: ansible_devices[item.device] is not defined
      loop: "{{ all_devices }}"
      loop_control:
        label: "{{ item.device}}"

    - name: install zfs and required tools
      apk:
        name: zfs,zfs-lts,lz4
        update_cache: true

    - name: create zfs pool
      zfs:
        name: pool
        state: present

    # todo: add zfs to /etc/modules and create zpool/datasets
    # zpool create -m none -o ashift=12 -O atime=off -O compression=lz4 {{ pool_name }} raidz1 {{ pool_devices }}