mqtt:
  host: mosquitto
  user: "{FRIGATE_MQTT_USER}"
  password: "{FRIGATE_MQTT_PASSWORD}"

go2rtc:
  streams:
    entrance_main:
      - "rtsp://{FRIGATE_CAMERA_USER}:{FRIGATE_CAMERA1_PASSWORD}@{FRIGATE_CAMERA1_HOST}:554/h264Preview_01_main"
      - "ffmpeg:entrance_main#audio=opus"
    bedroom_main:
      - "rtsp://{FRIGATE_CAMERA_USER}:{FRIGATE_CAMERA2_PASSWORD}@{FRIGATE_CAMERA2_HOST}:554/h264Preview_01_main"
      - "ffmpeg:bedroom_main#audio=opus"

# detectors:
#   coral:
#     type: edgetpu
#     device: ":0"

detect:
  enabled: false

record:
  enabled: false
  retain:
    days: 7
    mode: all

# ffmpeg:
#   input_args: preset-rtsp-restream
#   output_args:
#     record: preset-record-generic-audio-copy
#   hwaccel_args: preset-vaapi

cameras:
  entrance:
    ffmpeg:
      inputs:
        - path: "rtsp://127.0.0.1:8554/entrance_main"
          input_args: preset-rtsp-restream
          roles:
            - record
      output_args:
        record: preset-record-generic-audio-copy
      hwaccel_args: preset-vaapi
  bedroom:
    ffmpeg:
      inputs:
        - path: "rtsp://127.0.0.1:8554/bedroom_main"
          input_args: preset-rtsp-restream
          roles:
            - record
      output_args:
        record: preset-record-generic-audio-copy
      hwaccel_args: preset-vaapi
    record:
      enabled: false
