apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base
- pod.yml

configMapGenerator:
  - name: monitor-config
    envs: 
      - .env

generatorOptions:
  disableNameSuffixHash: true

replacements:
  - source:
      kind: ConfigMap
      name: monitor-config
      fieldPath: data.MONITOR_GRAFANA_DASHBOARD_FILE
    targets:
      - select:
          kind: Pod
          name: monitor
        fieldPaths:
          - spec.volumes.[name=grafana-dashboard-file].hostPath.path

  - source:
      kind: ConfigMap
      name: monitor-config
      fieldPath: data.MONITOR_GRAFANA_DATASOURCE_FILE
    targets:
      - select:
          kind: Pod
          name: monitor
        fieldPaths:
          - spec.volumes.[name=grafana-datasource-file].hostPath.path

  - source:
      kind: ConfigMap
      name: monitor-config
      fieldPath: data.MONITOR_PROMETHEUS_CONFIG_FILE
    targets:
      - select:
          kind: Pod
          name: monitor
        fieldPaths:
          - spec.volumes.[name=prometheus-config-file].hostPath.path

  - source:
      kind: ConfigMap
      name: monitor-config
      fieldPath: data.MONITOR_DIUN_CONFIG_FILE
    targets:
      - select:
          kind: Pod
          name: monitor
        fieldPaths:
          - spec.volumes.[name=diun-config].hostPath.path

  - source:
      kind: ConfigMap
      name: monitor-config
      fieldPath: data.MONITOR_DIUN_SOCKET_FILE
    targets:
      - select:
          kind: Pod
          name: monitor
        fieldPaths:
          - spec.volumes.[name=diun-socket].hostPath.path

  - source:
      kind: ConfigMap
      name: monitor-config
      fieldPath: data.MONITOR_NTFY_CONFIG_FILE
    targets:
      - select:
          kind: Pod
          name: monitor
        fieldPaths:
          - spec.volumes.[name=ntfy-config-file].hostPath.path