version: "3"

networks:
  public:
    name: ${NETWORK_PUBLIC}
  # private:
  #   name: ${NETWORK_PRIVATE}
  cloudflared:
    name: ${NETWORK_CLOUDFLARED}

services:
  caddy:
    image: caddy:local
    build:
      context: ./caddy
    restart: unless-stopped
    networks:
      - public
      - cloudflared
    volumes:
      - ./caddy/data:/data
      - ./caddy/config:/config
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
    ports:
      - 80:80
      - 443:443/tcp
      - 443:443/udp
    environment:
      - PUBLIC_DOMAIN=${PUBLIC_DOMAIN}
      - PRIVATE_DOMAIN=${PRIVATE_DOMAIN}
      - CF_API_EMAIL=${CF_API_EMAIL}
      - CF_API_TOKEN=${CF_API_TOKEN}

  cloudflared:
    image: docker.io/cloudflare/cloudflared:2022.10.2
    restart: unless-stopped
    command: tunnel --no-autoupdate run
    networks:
      - cloudflared
    environment:
      - TUNNEL_TOKEN=${CF_TUNNEL_TOKEN}