version: "3"

networks:
  public:
    name: ${NETWORK_PUBLIC}

volumes:
  jellyfin_cache:
  jellyfin_config:
  jellyfin_media:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ${JELLYFIN_MEDIA_PATH}

services:
  jellyfin:
    image: docker.io/jellyfin/jellyfin:10.8.5
    group_add:
      - ${JELLYFIN_VIDEO_GROUP}
    restart: unless-stopped
    networks:
      - public
    volumes:
      - jellyfin_cache:/config
      - jellyfin_config:/cache
      - jellyfin_media:/media
    devices:
      - ${JELLYFIN_CARD}:/dev/dri/card0
      - ${JELLYFIN_RENDER}:/dev/dri/renderD128