version: "3"

networks:
  public:
    name: ${NETWORK_PUBLIC}

services:
  traefik:
    image: docker.io/traefik:2.9.1
    restart: unless-stopped
    depends_on:
      - dockerproxy
    networks:
      - public
    volumes:
      - ./traefik:/etc/traefik
    ports:
      - 80:80
      - 443:443
      # dashboard
      # - 8080:8080
    environment:
      - CF_API_EMAIL=${CF_API_EMAIL}
      - CF_DNS_API_TOKEN=${CF_DNS_API_TOKEN}

  cloudflared:
    image: docker.io/cloudflare/cloudflared:2022.10.2
    restart: unless-stopped
    command: tunnel --no-autoupdate run
    networks:
      - public
    volumes:
      - ./cloudflared:/etc/cloudflared
    environment:
      - TUNNEL_TOKEN=${CF_TUNNEL_TOKEN}

  dockerproxy:
    image: ghcr.io/tecnativa/docker-socket-proxy:0.1
    restart: unless-stopped
    networks:
      - public
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - 2375
    environment:
      - CONTAINERS=1