# yaml-language-server: $schema=https://creativeprojects.github.io/resticprofile/jsonschema/config-2.json
version: "2"

profiles:
  frigate:
    inherit: default

    backup:
      schedule: weekly

      use:
        - name: stop-start-container
          container: frigate

      exclude:
        - model_cache/
        - frigate.db-shm
        - frigate.db-wal
      source:
        - /var/lib/docker/volumes/box_frigate-config

      tag:
        - docker

groups:
  tools:
    profiles:
      - frigate
