# yaml-language-server: $schema=https://creativeprojects.github.io/resticprofile/jsonschema/config-2.json
version: "2"

profiles:
  homeassistant:
    inherit: default

    backup:
      schedule: "weekly"

      use:
        - name: stop-start-container
          container: homeassistant

      exclude:
        - backups/
      source:
        - /var/lib/docker/volumes/box_home-assistant-config

      tag:
        - docker

groups:
  tools:
    profiles:
      - homeassistant
