# yaml-language-server: $schema=https://creativeprojects.github.io/resticprofile/jsonschema/config-2.json
version: "2"

profiles:
  homeassistant:
    inherit: default

    backup:
      schedule: weekly

      use:
        - name: stop-start-container
          container: homeassistant

      exclude:
        - backups/
        - home-assistant.log
        - home-assistant.log.1
        - home-assistant.log.fault
        - home-assistant_v2.db-shm
        - home-assistant_v2.db-wal
      source:
        - /var/lib/docker/volumes/box_home-assistant-config

      tag:
        - docker

groups:
  tools:
    profiles:
      - homeassistant
