# yaml-language-server: $schema=https://creativeprojects.github.io/resticprofile/jsonschema/config-2.json
version: "2"

profiles:
  immich:
    inherit: default

    backup:
      schedule: "03:00"
      check-before: true

      source:
        - /mnt/pool/immich

      tag:
        - private

    forget:
      schedule: "Sun 03:30"
      keep-within: "7d"
      prune: true

  immich-database:
    inherit: default

    backup:
      schedule: "03:10"

      use:
        - name: stop-start-container
          container: immich

      stdin: true
      stdin-command: docker compose -p box exec immich-database pg_dumpall -c -U postgres | gzip -c
      stdin-filename: "{{ .Profile.Name }}.sql.gz"

      tag:
        - private
        - sqldump

groups:
  media:
    profiles:
      - immich
      - immich-database
