# yaml-language-server: $schema=https://creativeprojects.github.io/resticprofile/jsonschema/config-2.json
version: "2"

profiles:
  navidrome-database:
    inherit: default

    backup:
      schedule: "weekly"

      use:
        - name: stop-start-container
          container: navidrome

      stdin: true
      stdin-command: gzip -c /var/lib/docker/volumes/box_navidrome-data/_data/navidrome.db
      stdin-filename: "{{ .Profile.Name }}.db.gz"

      tag:
        - docker
        - sqldump

groups:
  private:
    profiles:
      - navidrome-database
