# yaml-language-server: $schema=https://creativeprojects.github.io/resticprofile/jsonschema/config-1.json
version: "1"

paperless:
  inherit: default

  backup:
    schedule: "01:00"
    check-before: true

    run-before: docker compose -p box stop paperless
    run-finally: docker compose -p box start paperless

    source:
      # metadata and sqlite
      - /var/lib/docker/volumes/box_paperless-data
      # documents
      - /var/lib/docker/volumes/box_paperless-media

    tag:
      - "private"

  forget:
    schedule: "Sun 01:30"
    keep-last: 5
    prune: true
