# yaml-language-server: $schema=https://creativeprojects.github.io/resticprofile/jsonschema/config-2.json
version: "2"

profiles:
  paperless:
    inherit: default

    backup:
      schedule: "01:00"
      check-before: true

      source:
        # metadata
        - /var/lib/docker/volumes/box_paperless-data
        # documents
        - /var/lib/docker/volumes/box_paperless-media

      tag:
        - docker

    forget:
      schedule: "Sun 01:30"
      keep-last: 3
      prune: true

  paperless-database:
    inherit: default

    backup:
      schedule: "01:00"

      use:
        - name: stop-start-container
          container: paperless

      stdin: true
      stdin-command: docker compose -p box exec paperless-database pg_dumpall -c -U postgres | gzip -c
      stdin-filename: "{{ .Profile.Name }}.sql.gz"

      tag:
        - docker
        - sqldump

groups:
  private:
    profiles:
      - paperless
      - paperless-database
