# yaml-language-server: $schema=https://creativeprojects.github.io/resticprofile/jsonschema/config-2.json
version: "2"

profiles:
  paperless:
    inherit: default

    backup:
      schedule: "01:00"
      check-before: true

      use:
        - name: stop-start-container
          container: paperless

      source:
        # metadata and sqlite
        - /var/lib/docker/volumes/box_paperless-data
        # documents
        - /var/lib/docker/volumes/box_paperless-media

      tag:
        - private

    forget:
      schedule: "Sun 01:30"
      keep-last: 5
      prune: true

  # paperless-database:
  #   # todo: switch to postgress and use pg_dumpall instead

groups:
  docs:
    profiles:
      - paperless
