port: 53
httpPort: 4000

upstream:
  default:
    # quad9
    - 9.9.9.9
    - 149.112.112.112

customDNS:
  mapping:
    domain.tld: 10.10.0.10

blocking:
  blackLists:
    ads:
      - https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
  whiteLists:
    ads:
      - |
        # wifelist
        rd.rakuten.co.jp 
  clientGroupsBlock:
    default:
      - ads

prometheus:
  enable: true
