# yaml-language-server: $schema=https://creativeprojects.github.io/resticprofile/jsonschema/config-2.json
version: "2"

profiles:
  default:
    # make sure this exists and necessary vars are set, see default.env file
    env-file: "{{ .ConfigDir }}/.env"

    prometheus-save-to-file: "{{ .Env.HOME }}/textfile_collector/{{ .Profile.Name }}.prom"

    # note: for some reason this also causes notify-on-success to be inherited by all profiles
    # notify all failed backups by default
    # backup:
    #   use:
    #     - name: notify-on-fail
