- name: download frp
  ansible.builtin.get_url:
    url: "{{ frp_url }}"
    checksum: "{{ frp_checksum | default(omit) }}"
    dest: /tmp/frp.tar.gz
  retries: 3
  delay: 2

- name: extract fprs
  ansible.builtin.unarchive:
    src: /tmp/frp.tar.gz
    dest: "{{ frps_bin_dir }}"
    creates: "{{ frps_bin }}"
    remote_src: yes
    extra_opts: ["--strip-components=1"]
    # fixme: fails to extract for some reason
    # include: ["*/frps", "*/LICENSE"]

- name: create frp config directory
  ansible.builtin.file:
    path: "{{ frps_config_dir }}"
    state: directory
    mode: 0775

- name: render frps config
  ansible.builtin.template:
    src: frps.toml.j2
    dest: "{{ frps_config_path }}"

- name: install frps systemd service
  ansible.builtin.template:
    src: frps.service.j2
    dest: /etc/systemd/system/frps.service
    owner: root
    group: root
    mode: 0644

- name: start frps service
  ansible.builtin.systemd:
    name: frps
    state: started
    enabled: true
    daemon_reload: yes
