- name: preflight checks
  include_tasks: preflight.yml

- name: install required packages
  include_tasks: "packages-{{ ansible_pkg_mgr }}.yml"

- name: configure frps
  include_tasks: frps.yml

- name: configure firewall
  include_tasks: firewall.yml

- name: configure fail2ban
  include_tasks: fail2ban.yml

- name: configure caddy
  include_tasks: caddy.yml
